title: Data Séance
author: Don Walpola
email: dml.walpola@gmail.com
description: >- # this means to ignore newlines until next variable
  In depth coverage of topics and techniques in data science, machine learning,
  artificial intelligence, systems and computational biology, big data, and
  statistical methods - all from the perspective of a high-powered mutant of
  some kind never even considered for mass production. The personal website of
  Don Walpola.
permalink: /blog/:year/:month/:day/:title
highlighter: rouge

# Social media usernames
twitter_username: DonWalpola
github_username: Phenomedon
facebook_username: don.m.l.walpola
instagram_username: donwalpola
linkedin_username: don-Walpola
kaggle_username: robonimo86
stackoverflow_username: "users/218088/"

# Collections structure
collections:
  elements:
    output: true
    permalink: /elements/:path/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
